### ISSUE TITLE
.themes/Everblush-xfwm/xfwm4/themerc

### ISSUE THREAD

**Issue by ERFouX** [mwarevn/theme-kali-lincox#1]
/.themes/Everblush-xfwm/xfwm4/themerc

My problem is that it doesn't change when the cursor is in the corner of the window and I can only resize the window vertically / or only horizontally - I want to resize both horizontally and vertically at the same time as I grab the corner of the window

**Comment by mwarevn** [comment]
Sorry for that but I really don't know how to fix the problem you're having. I found this theme on youtube and this repo is just a tool I created to help me automatically install the theme without having to review the instructions. You can follow the step by step instructions on YouTube to make sure the theme works properly. sorry for my bad translated english

[Video tutorial on youtube](https://www.youtube.com/watch?v=ZIRlfaP_SB4&t=202s)

**Comment by ERFouX** [comment]
To be honest, I did the config from the same video and then I realized that I could do it much easier with your repository - anyway, thanks a lot for your reply mate.
